### ISSUE TITLE
Export of project assessments

### ISSUE THREAD

**Issue by karstenpeters** [MaayanLab/FAIRshake#159] opened 2021-06-18 09:06 UTC
Hi, is there a possibility to export the results of assessments in the form of a table or csv file? If not, would it be feasible to have such a feature implemented? Thanks! Cheers, Karsten

**Comment by u8sand** [comment] 2021-06-18 14:15
Duplicate of #121  But yes, we plan on adding this very soon.

**Closed by u8sand** 2021-06-18 14:15 UTC
